### ISSUE TITLE
01 - fix docker compose

### ISSUE THREAD

**Issue by fedefailla18** [fedefailla18/file-importer#10]

**Comment by fedefailla18** [comment]
https://medium.com/@asuarezaceves/initializing-a-postgresql-database-with-a-dataset-using-docker-compose-a-step-by-step-guide-3feebd5b1545

https://www.postgresql.org/docs/current/sql-createsequence.html

**Comment by fedefailla18** [comment]
https://github.com/fedefailla18/file-importer/pull/11

**Comment by facum15** [comment]
Added changes and a script to make it work correctly
